name:                reddit-emacs-tips-n-tricks
version:             0.1.0.0
github:              "githubuser/reddit-emacs-tips-n-tricks"
license:             MIT
author:              "Laurence Warne"
maintainer:          "laurencewarne@gmail.com"
copyright:           "2022 Laurence Warne"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/laurencewarne/reddit-emacs-tips-n-tricks#readme>

dependencies:
- base >= 4.7 && < 5
- text
- reddit
- raw-strings-qq

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  reddit-emacs-tips-n-tricks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -static
    - -optl-pthread
    - -optl-static
    dependencies:
    - reddit-emacs-tips-n-tricks

tests:
  reddit-emacs-tips-n-tricks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - reddit-emacs-tips-n-tricks
    - raw-strings-qq
