resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/28.yaml

packages:
- .
  
extra-deps:
- reddit-0.3.0.0
- aeson-2.1.0.0
- api-builder-0.17.0.0
- OneTuple-0.3.1
- attoparsec-0.14.4
- generically-0.1
- hashable-1.4.1.0
- semialign-1.2.0.1
- text-short-0.1.5
- time-compat-1.9.6.1
