on: [push]
name: build
jobs:
  runhaskell:

    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.8.4' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'

      - name: Build Executable
        id: build-exec
        run: |
          stack build
          echo "::set-output name=bin-path::$(stack path --local-install-root)"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build-exec.outputs.bin-path }}/bin/reddit-emacs-tips-n-tricks-exe
          #files: .stack-work/dist/x86_64-linux/Cabal-${{ cabal-version }}/build/reddit-emacs-tips-n-tricks-exe/reddit-emacs-tips-n-tricks-exe
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
