on:
  workflow_dispatch:

name: Deploy

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest    

    permissions:
      id-token: write
      contents: read
    
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GITHUB_SHA }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: tips-n-tricks-lambda
          template: lambda/templates/template.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "BaseStackName=base,CodeKey=tips-n-tricks-lambda.zip,LayerKey=tips-n-tricks-exe.zip,GithubPAT=${{ secrets.GH_PAT }}"
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
 
